FROM syscoin-ubuntu-build

RUN (cd syscoin  && ./autogen.sh && \
                    ./configure --without-gui \
                    --with-incompatible-bdb && \
                    make -j$(nproc) -pipe && \
                    make install )
